### ISSUE TITLE
Expand client-server interaction in submitting posts/events

### ISSUE THREAD

**Issue by tvquizphd** [green-rainbow-org/new-green-layout#4]
This is the first issue that we'll resolve before we can move forward. When submitting the form, the javascript client currently submits no information to the event API, and it submits only these three fields for the basic page API:

```js
{
    content, name: 'page',
    published: false
}
```

### Tasks for this Issue

- [ ] The client should give a real name, rather than `'page'` for each page .
- [ ] Our API should also use optional fields (ie, `slug`, `title`, `headline`, `tags`).
- [ ] The `event` API should be used by the client on each "event" submission.

@michaellavery-grp, this added use of the `event` API is where I could use the most help. For now, I would like feedback on the basic structure of the existing code: the model [`event.py`](https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/util/models/event.py), its use in [`api.py` lines 132 - 159](https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/api/api/api.py#L132), and its use in [`mockup.py` lines 86 - 118](https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/mockup/mockup/mockup.py#L86).  Importantly, Instead of a database, the Nationbuilder mock-up uses [`state.py`](https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/mockup/state/state.py) to write all stored data to JSON on the local file system. These files are ignored by git.

The `event` API is implemented in both the python `api.py` and `mockup.py`. The full nation builder [event API is defined here](https://nationbuilder.com/events_api), of which we use a subset, defined in [`event.py`](https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/util/models/event.py). Also, this is the  full [basic pages API](https://nationbuilder.com/basic_pages_api). We also only use a subset, defined in [`basic_page.py`](https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/util/models/basic_page.py). 

## Current client-server interactions

- The Nationbuilder [`mockup` server][mock] is ready to send/receive/store data
- The [`api` server][api] is ready to communicate between the client and the mockup

Now, it's up to the JS client to use these resources effectively.

This is done on "Submit" in a limited way already:
  - The [submitPage in actions.js][action] is called when submitting
  - The [sendBasicPage api in api.js][basic_page] is called by submitPage
  - Then [submitPage][nav] returns the new complete list of pages

[mock]: https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/mockup/mockup/mockup.py
[api]: https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/api/api/api.py
[action]: https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/client/src/lib/actions.js
[basic_page]: https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/client/src/lib/api.js
[nav]: https://github.com/green-rainbow-org/new-green-layout/blob/b636c6b601e13c0a362fdb39a5bec01032d0eff0/client/src/nav/nav.js#L73

**Comment by michaellavery-grp** [comment]
@tvquizphd Sorry for the delay . I have had more time tonight to look at the code. My main issue was getting the ``pydantic`` Python module to work . They must have done some updates recently because I had to change some pydantic modules to ``pydantic_settings`` in the import section. I would push the code back to the repo, but I don't have permissions. Can you add me to the members? I forked a new branch , so I won't overwrite anything... Thanks, Mike L.
